In [1]:
import pandas as pd

In [2]:
ratings1=pd.read_csv('data/ratings1.csv')
ratings2=pd.read_csv('data/ratings2.csv')
dates=pd.read_csv('data/dates.csv')
movies=pd.read_csv('data/movies.csv')

In [3]:
ratings1.head(3)

   userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0

In [4]:
movies.head(3)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance

In [5]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

In [6]:
movies['movieId'].nunique()

9742

In [7]:
ratings1['userId'].nunique()

274

In [8]:
dates.head()

                  date
0  2000-07-30 18:45:03
1  2000-07-30 18:20:47
2  2000-07-30 18:37:04
3  2000-07-30 19:03:35
4  2000-07-30 18:48:51

In [9]:
dates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 1 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    100836 non-null  object
dtypes: object(1)
memory usage: 787.9+ KB

In [10]:
dates['date']=pd.to_datetime(dates['date'],format = '%Y-%m-%d %H:%M:%S')

In [11]:
dates.head(2)

                 date
0 2000-07-30 18:45:03
1 2000-07-30 18:20:47

In [12]:
(dates['date'].dt.year).mode()

0    2000
Name: date, dtype: int32

In [13]:
dates['date'].dt.year.value_counts()

date
2000    10061
2017     8198
2007     7114
2016     6703
2015     6616
2018     6418
1996     6040
2005     5813
2012     4656
2008     4351
2009     4158
2006     4059
2003     4014
2001     3922
2002     3478
2004     3279
1999     2439
2010     2301
1997     1916
2011     1690
2013     1664
2014     1439
1998      507
Name: count, dtype: int64

In [14]:
ratings=pd.concat([ratings1,ratings2])

In [15]:
ratings1.shape

(40001, 3)

In [16]:
ratings2.shape

(60836, 3)

In [17]:
ratings=pd.concat([ratings1,ratings2],ignore_index=True)

In [18]:
ratings

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100832     610   166534     4.0
100833     610   168248     5.0
100834     610   168250     5.0
100835     610   168252     5.0
100836     610   170875     3.0

[100837 rows x 3 columns]

In [19]:
print('Число строк в таблице ratings: ', ratings.shape[0])
print('Число строк в таблице dates: ', dates.shape[0])
print(ratings.shape[0] == dates.shape[0])

# Число строк в таблице ratings: 100837
# Число строк в таблице dates: 100836
# False

Число строк в таблице ratings:  100837
Число строк в таблице dates:  100836
False

In [20]:
display(ratings1.tail(1))
display(ratings2.head(1))

       userId  movieId  rating
40000     274     5621     2.0

   userId  movieId  rating
0     274     5621     2.0

In [21]:
ratings=ratings.drop_duplicates(ignore_index=True)

In [22]:
print(f'Число строк в таблице рейтингс: {ratings.shape[0]}.\nЧисло строк в таблице дейт:{dates.shape[0]}')

Число строк в таблице рейтингс: 100836.
Число строк в таблице дейт:100836

In [23]:
ratings_dates=pd.concat([ratings,dates],axis=1)

In [24]:
display(ratings_dates.tail(7))

        userId  movieId  rating                date
100829     610   164179     5.0 2017-05-03 21:07:11
100830     610   166528     4.0 2017-05-04 06:29:25
100831     610   166534     4.0 2017-05-03 21:53:22
100832     610   168248     5.0 2017-05-03 22:21:31
100833     610   168250     5.0 2017-05-08 19:50:47
100834     610   168252     5.0 2017-05-03 21:19:12
100835     610   170875     3.0 2017-05-03 21:20:15

In [25]:
list1=['users2.csv', 'users1.csv', 'users3.csv']
print(sorted(list1))

['users1.csv', 'users2.csv', 'users3.csv']

In [27]:
ratings_dates.head()

   userId  movieId  rating                date
0       1        1     4.0 2000-07-30 18:45:03
1       1        3     4.0 2000-07-30 18:20:47
2       1        6     4.0 2000-07-30 18:37:04
3       1       47     5.0 2000-07-30 19:03:35
4       1       50     5.0 2000-07-30 18:48:51

In [26]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [28]:
ratings_dates.shape

(100836, 4)

In [29]:
movies.shape

(9742, 3)

In [33]:
joinedfalse=ratings_dates.join(
    movies,
    rsuffix='_right',
    how='left')

In [34]:
joinedfalse

,userId,movieId,rating,date,movieId_right,title,genres
0,1,1,4.0,2000-07-30 18:45:03,1.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,2.0,Jumanji (1995),Adventure|Children|Fantasy
2,1,6,4.0,2000-07-30 18:37:04,3.0,Grumpier Old Men (1995),Comedy|Romance
3,1,47,5.0,2000-07-30 19:03:35,4.0,Waiting to Exhale (1995),Comedy|Drama|Romance
4,1,50,5.0,2000-07-30 18:48:51,5.0,Father of the Bride Part II (1995),Comedy
...,...,...,...,...,...,...,...
100831,610,166534,4.0,2017-05-03 21:53:22,NaN,NaN,NaN
100832,610,168248,5.0,2017-05-03 22:21:31,NaN,NaN,NaN
100833,610,168250,5.0,2017-05-08 19:50:47,NaN,NaN,NaN
100834,610,168252,5.0,2017-05-03 21:19:12,NaN,NaN,NaN
100835,610,170875,3.0,2017-05-03 21:20:15,NaN,NaN,NaN

In [35]:
joinedfalse=ratings_dates.join(
    movies,
    rsuffix='_right',
    how='right')
joinedfalse

,userId,movieId,rating,date,movieId_right,title,genres
0,1,1,4.0,2000-07-30 18:45:03,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,2,Jumanji (1995),Adventure|Children|Fantasy
2,1,6,4.0,2000-07-30 18:37:04,3,Grumpier Old Men (1995),Comedy|Romance
3,1,47,5.0,2000-07-30 19:03:35,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,1,50,5.0,2000-07-30 18:48:51,5,Father of the Bride Part II (1995),Comedy
...,...,...,...,...,...,...,...
9737,64,3481,4.0,2006-10-22 12:37:45,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,64,3489,3.0,2006-10-22 23:28:09,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,64,3499,4.5,2006-10-22 23:26:41,193585,Flint (2017),Drama
9740,64,3510,3.0,2006-10-22 23:27:26,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,64,3526,4.0,2006-10-23 01:23:47,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [36]:
joinedfalse=ratings_dates.join(
    movies,
    rsuffix='_right',
    how='inner')
joinedfalse

,userId,movieId,rating,date,movieId_right,title,genres
0,1,1,4.0,2000-07-30 18:45:03,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,2,Jumanji (1995),Adventure|Children|Fantasy
2,1,6,4.0,2000-07-30 18:37:04,3,Grumpier Old Men (1995),Comedy|Romance
3,1,47,5.0,2000-07-30 19:03:35,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,1,50,5.0,2000-07-30 18:48:51,5,Father of the Bride Part II (1995),Comedy
...,...,...,...,...,...,...,...
9737,64,3481,4.0,2006-10-22 12:37:45,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,64,3489,3.0,2006-10-22 23:28:09,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,64,3499,4.5,2006-10-22 23:26:41,193585,Flint (2017),Drama
9740,64,3510,3.0,2006-10-22 23:27:26,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,64,3526,4.0,2006-10-23 01:23:47,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [38]:
joinedfalse=ratings_dates.join(
    movies,
    rsuffix='_right',
    how='outer')
joinedfalse

,userId,movieId,rating,date,movieId_right,title,genres
0,1,1,4.0,2000-07-30 18:45:03,1.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,2.0,Jumanji (1995),Adventure|Children|Fantasy
2,1,6,4.0,2000-07-30 18:37:04,3.0,Grumpier Old Men (1995),Comedy|Romance
3,1,47,5.0,2000-07-30 19:03:35,4.0,Waiting to Exhale (1995),Comedy|Drama|Romance
4,1,50,5.0,2000-07-30 18:48:51,5.0,Father of the Bride Part II (1995),Comedy
...,...,...,...,...,...,...,...
100831,610,166534,4.0,2017-05-03 21:53:22,NaN,NaN,NaN
100832,610,168248,5.0,2017-05-03 22:21:31,NaN,NaN,NaN
100833,610,168250,5.0,2017-05-08 19:50:47,NaN,NaN,NaN
100834,610,168252,5.0,2017-05-03 21:19:12,NaN,NaN,NaN
100835,610,170875,3.0,2017-05-03 21:20:15,NaN,NaN,NaN

In [40]:
movies.set_index('movieId')

,title,genres
movieId,,
1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,Jumanji (1995),Adventure|Children|Fantasy
3,Grumpier Old Men (1995),Comedy|Romance
4,Waiting to Exhale (1995),Comedy|Drama|Romance
5,Father of the Bride Part II (1995),Comedy
...,...,...
193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
193585,Flint (2017),Drama
193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [41]:
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [43]:
joined = ratings_dates.join(
    movies.set_index('movieId'),
    on='movieId',
    how = 'left'
)
joined

,userId,movieId,rating,date,title,genres
0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
...,...,...,...,...,...,...
100831,610,166534,4.0,2017-05-03 21:53:22,Split (2017),Drama|Horror|Thriller
100832,610,168248,5.0,2017-05-03 22:21:31,John Wick: Chapter Two (2017),Action|Crime|Thriller
100833,610,168250,5.0,2017-05-08 19:50:47,Get Out (2017),Horror
100834,610,168252,5.0,2017-05-03 21:19:12,Logan (2017),Action|Sci-Fi
100835,610,170875,3.0,2017-05-03 21:20:15,The Fate of the Furious (2017),Action|Crime|Drama|Thriller

In [44]:
merged=ratings_dates.merge(
    movies,
    on='movieId',
    how='left'
)
merged

,userId,movieId,rating,date,title,genres
0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
...,...,...,...,...,...,...
100831,610,166534,4.0,2017-05-03 21:53:22,Split (2017),Drama|Horror|Thriller
100832,610,168248,5.0,2017-05-03 22:21:31,John Wick: Chapter Two (2017),Action|Crime|Thriller
100833,610,168250,5.0,2017-05-08 19:50:47,Get Out (2017),Horror
100834,610,168252,5.0,2017-05-03 21:19:12,Logan (2017),Action|Sci-Fi
100835,610,170875,3.0,2017-05-03 21:20:15,The Fate of the Furious (2017),Action|Crime|Drama|Thriller

In [45]:
items_df = pd.DataFrame({
            'item_id': [417283, 849734, 132223, 573943, 19475, 3294095, 382043, 302948, 100132, 312394],
            'vendor': ['Samsung', 'LG', 'Apple', 'Apple', 'LG', 'Apple', 'Samsung', 'Samsung', 'LG', 'ZTE'],
            'stock_count': [54, 33, 122, 18, 102, 43, 77, 143, 60, 19]
        })

purchase_df = pd.DataFrame({
            'purchase_id': [101, 101, 101, 112, 121, 145, 145, 145, 145, 221],
            'item_id': [417283, 849734, 132223, 573943, 19475, 3294095, 382043, 302948, 103845, 100132],
            'price': [13900, 5330, 38200, 49990, 9890, 33000, 67500, 34500, 89900, 11400]
        })

In [47]:
merged2=items_df.merge(purchase_df,
                       on='item_id',
                       how='inner')
merged2

   item_id   vendor  stock_count  purchase_id  price
0   417283  Samsung           54          101  13900
1   849734       LG           33          101   5330
2   132223    Apple          122          101  38200
3   573943    Apple           18          112  49990
4    19475       LG          102          121   9890
5  3294095    Apple           43          145  33000
6   382043  Samsung           77          145  67500
7   302948  Samsung          143          145  34500
8   100132       LG           60          221  11400

In [53]:
income=sum(merged2['price']*merged2['stock_count'])
income

19729490

In [54]:
import re 
def get_year_release(arg):
    #находим все слова по шаблону "(DDDD)"
    candidates = re.findall(r'\(\d{4}\)', arg) 
    # проверяем число вхождений
    if len(candidates) > 0:
        #если число вхождений больше 0,
	#очищаем строку от знаков "(" и ")"
        year = candidates[0].replace('(', '')
        year = year.replace(')', '')
        return int(year)
    else:
        #если год не указан, возвращаем None
        return None

In [56]:
merged['year_release']=merged['title'].apply(get_year_release)

In [57]:
merged

,userId,movieId,rating,date,title,genres,year_release
0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995.0
1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance,1995.0
2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller,1995.0
3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,1995.0
4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,1995.0
...,...,...,...,...,...,...,...
100831,610,166534,4.0,2017-05-03 21:53:22,Split (2017),Drama|Horror|Thriller,2017.0
100832,610,168248,5.0,2017-05-03 22:21:31,John Wick: Chapter Two (2017),Action|Crime|Thriller,2017.0
100833,610,168250,5.0,2017-05-08 19:50:47,Get Out (2017),Horror,2017.0
100834,610,168252,5.0,2017-05-03 21:19:12,Logan (2017),Action|Sci-Fi,2017.0
100835,610,170875,3.0,2017-05-03 21:20:15,The Fate of the Furious (2017),Action|Crime|Drama|Thriller,2017.0

In [131]:
merged['year_release'].sort_values(ascending=False)

71998    2018.0
36357    2018.0
34909    2018.0
90225    2018.0
37416    2018.0
          ...
71984       NaN
81445       NaN
83380       NaN
88136       NaN
95078       NaN
Name: year_release, Length: 100836, dtype: float64

In [60]:
merged.isna().sum()

userId           0
movieId          0
rating           0
date             0
title            0
genres           0
year_release    18
dtype: int64

In [61]:
merged.isnull().sum()

userId           0
movieId          0
rating           0
date             0
title            0
genres           0
year_release    18
dtype: int64

In [74]:
ratingmerge=merged[merged['year_release']==1999.0].loc[:,['title','rating']]

In [81]:
ratingmerge.groupby(by='title').mean().sort_values(by='rating')

                                            rating
title
Bloodsport: The Dark Kumite (1999)             0.5
Simon Sez (1999)                               1.0
Chill Factor (1999)                            1.0
Source, The (1999)                             1.0
Trippin' (1999)                                1.0
...                                            ...
Trailer Park Boys (1999)                       5.0
Larry David: Curb Your Enthusiasm (1999)       5.0
Sun Alley (Sonnenallee) (1999)                 5.0
George Carlin: You Are All Diseased (1999)     5.0
Five Senses, The (1999)                        5.0

[261 rows x 1 columns]

In [99]:
merg2010=merged[merged['year_release']==2010.0]

In [100]:
merg2010.groupby(by='genres')['rating'].mean().sort_values()

genres
Action|Sci-Fi                        1.000000
Action|Adventure|Horror              1.500000
Action|Drama|Fantasy                 1.500000
Crime|Romance                        1.500000
Adventure|Comedy|Fantasy             1.833333
                                       ...
Crime                                4.750000
Comedy|Musical                       5.000000
Animation|Drama|Fantasy|Mystery      5.000000
Adventure|Children|Comedy|Mystery    5.000000
Animation|Children|Mystery           5.000000
Name: rating, Length: 119, dtype: float64

In [103]:
merged.groupby(by='userId')['genres'].nunique().sort_values(ascending=False)

userId
599    524
414    482
448    403
380    399
474    395
      ...
578     15
12      15
85      13
214     13
245     13
Name: genres, Length: 610, dtype: int64

In [114]:
mergedid=merged.groupby(by='userId')[['movieId','rating']].agg(['count','mean'])

In [116]:
mergedid

       movieId               rating
         count          mean  count      mean
userId
1          232   1854.603448    232  4.366379
2           29  70350.275862     29  3.948276
3           39   7058.384615     39  2.435897
4          216   1982.129630    216  3.555556
5           44    343.840909     44  3.636364
...        ...           ...    ...       ...
606       1115   9692.197309   1115  3.657399
607        187   1860.636364    187  3.786096
608        831   4502.605295    831  3.134176
609         37    483.162162     37  3.270270
610       1302  49590.231183   1302  3.688556

[610 rows x 4 columns]

In [126]:
mergedid['rating'][['count','mean']].sort_values(by=['count','mean'],ascending=[True,False])

        count      mean
userId
53         20  5.000000
595        20  4.200000
189        20  4.100000
569        20  4.000000
278        20  3.875000
...       ...       ...
274      1346  3.235884
448      1864  2.847371
474      2108  3.398956
599      2478  2.642050
414      2698  3.391957

[610 rows x 2 columns]

In [133]:
filteredyear2018=merged[merged['year_release'] == 2018.0]

In [134]:
mergedgenres=filteredyear2018.groupby(by='genres')['rating'].agg(['count','mean'])

In [136]:
mergedgenres[mergedgenres['count']>10].sort_values(by='mean',ascending=False)

                         count      mean
genres
Action|Adventure|Sci-Fi     14  3.928571
Action|Comedy|Sci-Fi        12  3.875000

In [137]:
merged['year_rating']=merged['date'].dt.year

In [138]:
merged

,userId,movieId,rating,date,title,genres,year_release,year_rating
0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995.0,2000
1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance,1995.0,2000
2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller,1995.0,2000
3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,1995.0,2000
4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,1995.0,2000
...,...,...,...,...,...,...,...,...
100831,610,166534,4.0,2017-05-03 21:53:22,Split (2017),Drama|Horror|Thriller,2017.0,2017
100832,610,168248,5.0,2017-05-03 22:21:31,John Wick: Chapter Two (2017),Action|Crime|Thriller,2017.0,2017
100833,610,168250,5.0,2017-05-08 19:50:47,Get Out (2017),Horror,2017.0,2017
100834,610,168252,5.0,2017-05-03 21:19:12,Logan (2017),Action|Sci-Fi,2017.0,2017
100835,610,170875,3.0,2017-05-03 21:20:15,The Fate of the Furious (2017),Action|Crime|Drama|Thriller,2017.0,2017

In [142]:
mergedpivot=merged.pivot_table(
    values='rating',
    index='genres',
    columns = 'year_rating',
    aggfunc='mean',
    fill_value=0
)

In [143]:
mergedpivot

year_rating,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
genres,,,,,,,,,,,,,,,,,,,,,
(no genres listed),0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.500000,3.500000,3.000000,3.676471
Action,2.730769,3.538462,0.0,0.0,2.588235,3.000000,2.750000,3.833333,2.700000,3.357143,...,0.000000,3.500000,4.500000,2.625000,2.500000,0.000,3.100000,3.545455,2.637931,2.588235
Action|Adventure,3.454545,4.150000,4.2,4.0,3.738462,3.500000,4.304348,3.277778,4.136364,3.413043,...,3.714286,3.437500,3.888889,3.900000,3.833333,3.875,3.560976,3.722222,3.527778,3.397436
Action|Adventure|Animation,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,3.000,3.800000,3.750000,3.375000,3.650000
Action|Adventure|Animation|Children,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,4.000000,3.000000,3.500,3.666667,3.833333,3.500000,3.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sci-Fi|Thriller,2.666667,3.400000,0.0,4.0,2.142857,2.500000,3.600000,3.142857,0.000000,2.750000,...,4.000000,2.500000,1.833333,3.500000,3.833333,0.000,3.764706,3.916667,3.750000,3.562500
Sci-Fi|Thriller|IMAX,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,4.000000,3.666667,4.000000,4.000,4.000000,3.666667,2.500000,0.000000
Thriller,3.838095,3.923077,3.8,3.7,3.087912,3.477273,3.583333,3.250000,3.464286,3.411765,...,2.964286,2.833333,3.625000,3.083333,3.666667,4.000,2.911765,3.432432,3.152174,3.296296
War,0.000000,0.000000,0.0,4.5,3.000000,3.000000,3.500000,3.000000,3.000000,0.000000,...,4.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000
Western,3.117647,3.000000,0.0,4.0,4.058824,3.111111,3.000000,4.000000,3.800000,4.500000,...,3.375000,3.666667,4.000000,4.100000,4.000000,4.000,3.900000,3.958333,2.933333,3.611111

In [146]:
mergedpivot.loc['Action|Adventure|Animation|Children|Comedy|IMAX',:].sort_values()

year_rating
1996    0.000000
2011    0.000000
2008    0.000000
2006    0.000000
2005    0.000000
2004    0.000000
2003    0.000000
2007    0.000000
2001    0.000000
2000    0.000000
1999    0.000000
1998    0.000000
1997    0.000000
2002    0.000000
2017    1.000000
2009    3.250000
2015    3.375000
2010    3.500000
2014    3.500000
2012    3.550000
2016    3.666667
2018    3.700000
2013    5.000000
Name: Action|Adventure|Animation|Children|Comedy|IMAX, dtype: float64

In [ ]:
mergedpivot.loc['Action|Adventure',:]

In [152]:
'Animation|Children|Mystery' in (mergedpivot.loc[:,2018].sort_values(ascending=False).head(30))

True

In [153]:
mergedpivot.loc['Comedy',:]

year_rating
1996    3.228571
1997    3.409091
1998    3.000000
1999    3.606061
2000    3.141291
2001    3.318408
2002    3.198556
2003    3.120066
2004    3.356877
2005    2.963325
2006    3.347534
2007    2.928187
2008    3.426667
2009    3.273292
2010    3.179825
2011    3.232877
2012    3.478477
2013    3.489474
2014    3.271429
2015    3.106183
2016    3.373431
2017    2.852668
2018    3.121296
Name: Comedy, dtype: float64

In [156]:
products=pd.read_csv('data/products.csv',sep=';')
orders=pd.read_csv('data/orders.csv',sep=';')

In [157]:
products.head()

   Product_ID                      Name  Price CURRENCY
0          47      Шатны Полосатый рейс   2999      RUR
1          51  Платье Аленький цветочек   4999      RUR
2          53    Штаны Цветочная Поляна   4999      RUR
3          71       Платье Ночная Жизнь   7999      RUR
4          74  Платье Ночная Жизнь XXXL   8999      RUR

In [158]:
orders.head()

,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество
0,09.11.2019 21:55:51,9,10,"Принят, ожидается оплата",Нет,Нет,Нет,103,5
1,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,86,100
2,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,104,10
3,09.11.2019 12:50:07,7,8,"Принят, ожидается оплата",Нет,Нет,Нет,104,7
4,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,104,5

In [160]:
orders_products=orders.merge(products,left_on='ID товара',right_on='Product_ID',how='left')

In [161]:
orders_products

,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество,Product_ID,Name,Price,CURRENCY
0,09.11.2019 21:55:51,9,10,"Принят, ожидается оплата",Нет,Нет,Нет,103,5,103.0,"Носки Подарочные, муж",199.0,RUR
1,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,86,100,86.0,"Носки Простые, муж",45.0,RUR
2,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,104,10,104.0,"Носки Подарочные, жен",249.0,RUR
3,09.11.2019 12:50:07,7,8,"Принят, ожидается оплата",Нет,Нет,Нет,104,7,104.0,"Носки Подарочные, жен",249.0,RUR
4,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,104,5,104.0,"Носки Подарочные, жен",249.0,RUR
5,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,103,5,103.0,"Носки Подарочные, муж",199.0,RUR
6,08.11.2019 08:36:22,5,5,Отменён,Нет,Да,Нет,124,1,124.0,Носки беговые Camino,999.0,RUR
7,08.11.2019 08:36:22,4,9,"Принят, ожидается оплата",Нет,Нет,Да,91,1,91.0,"Носки Честные, муж",50.0,RUR
8,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,103,3,103.0,"Носки Подарочные, муж",199.0,RUR
9,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,104,3,104.0,"Носки Подарочные, жен",249.0,RUR
10,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,74,1,74.0,Платье Ночная Жизнь XXXL,8999.0,RUR
11,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,53,1,53.0,Штаны Цветочная Поляна,4999.0,RUR
12,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,137,1,137.0,Гольфы детские Снегурочка,99.0,RUR
13,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,47,1,47.0,Шатны Полосатый рейс,2999.0,RUR
14,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,71,1,71.0,Платье Ночная Жизнь,7999.0,RUR
15,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,86,1,86.0,"Носки Простые, муж",45.0,RUR
16,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,51,1,51.0,Платье Аленький цветочек,4999.0,RUR
17,01.01.2001 00:00:00,0,1,"Оплачен, формируется к отправке",Да,Нет,Нет,666,1,NaN,NaN,NaN,NaN

In [162]:
orders_products2=orders_products.drop('Product_ID',axis=1)

In [163]:
orders_products2

,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество,Name,Price,CURRENCY
0,09.11.2019 21:55:51,9,10,"Принят, ожидается оплата",Нет,Нет,Нет,103,5,"Носки Подарочные, муж",199.0,RUR
1,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,86,100,"Носки Простые, муж",45.0,RUR
2,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,104,10,"Носки Подарочные, жен",249.0,RUR
3,09.11.2019 12:50:07,7,8,"Принят, ожидается оплата",Нет,Нет,Нет,104,7,"Носки Подарочные, жен",249.0,RUR
4,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,104,5,"Носки Подарочные, жен",249.0,RUR
5,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,103,5,"Носки Подарочные, муж",199.0,RUR
6,08.11.2019 08:36:22,5,5,Отменён,Нет,Да,Нет,124,1,Носки беговые Camino,999.0,RUR
7,08.11.2019 08:36:22,4,9,"Принят, ожидается оплата",Нет,Нет,Да,91,1,"Носки Честные, муж",50.0,RUR
8,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,103,3,"Носки Подарочные, муж",199.0,RUR
9,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,104,3,"Носки Подарочные, жен",249.0,RUR
10,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,74,1,Платье Ночная Жизнь XXXL,8999.0,RUR
11,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,53,1,Штаны Цветочная Поляна,4999.0,RUR
12,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,137,1,Гольфы детские Снегурочка,99.0,RUR
13,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,47,1,Шатны Полосатый рейс,2999.0,RUR
14,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,71,1,Платье Ночная Жизнь,7999.0,RUR
15,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,86,1,"Носки Простые, муж",45.0,RUR
16,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,51,1,Платье Аленький цветочек,4999.0,RUR
17,01.01.2001 00:00:00,0,1,"Оплачен, формируется к отправке",Да,Нет,Нет,666,1,NaN,NaN,NaN

In [168]:
orders_products3=orders_products2.copy()
orders_products3['Прибыль']=orders_products3['Price'] * orders_products3['Количество']
orders_products3

,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество,Name,Price,CURRENCY,Прибыль
0,09.11.2019 21:55:51,9,10,"Принят, ожидается оплата",Нет,Нет,Нет,103,5,"Носки Подарочные, муж",199.0,RUR,995.0
1,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,86,100,"Носки Простые, муж",45.0,RUR,4500.0
2,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,104,10,"Носки Подарочные, жен",249.0,RUR,2490.0
3,09.11.2019 12:50:07,7,8,"Принят, ожидается оплата",Нет,Нет,Нет,104,7,"Носки Подарочные, жен",249.0,RUR,1743.0
4,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,104,5,"Носки Подарочные, жен",249.0,RUR,1245.0
5,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,103,5,"Носки Подарочные, муж",199.0,RUR,995.0
6,08.11.2019 08:36:22,5,5,Отменён,Нет,Да,Нет,124,1,Носки беговые Camino,999.0,RUR,999.0
7,08.11.2019 08:36:22,4,9,"Принят, ожидается оплата",Нет,Нет,Да,91,1,"Носки Честные, муж",50.0,RUR,50.0
8,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,103,3,"Носки Подарочные, муж",199.0,RUR,597.0
9,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,104,3,"Носки Подарочные, жен",249.0,RUR,747.0
10,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,74,1,Платье Ночная Жизнь XXXL,8999.0,RUR,8999.0
11,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,53,1,Штаны Цветочная Поляна,4999.0,RUR,4999.0
12,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,137,1,Гольфы детские Снегурочка,99.0,RUR,99.0
13,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,47,1,Шатны Полосатый рейс,2999.0,RUR,2999.0
14,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,71,1,Платье Ночная Жизнь,7999.0,RUR,7999.0
15,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,86,1,"Носки Простые, муж",45.0,RUR,45.0
16,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,51,1,Платье Аленький цветочек,4999.0,RUR,4999.0
17,01.01.2001 00:00:00,0,1,"Оплачен, формируется к отправке",Да,Нет,Нет,666,1,NaN,NaN,NaN,NaN

In [171]:
orders_productspaid=orders_products3[(orders_products3['Статус'] == 'Оплачен, формируется к отправке') | (orders_products3['Статус'] == 'Выполнен')]

In [177]:
orders_productspaid.groupby('ID Покупателя')['Прибыль'].sum()

ID Покупателя
1        0.0
5    13043.0
7    17096.0
8     1344.0
Name: Прибыль, dtype: float64